### PR TITLE
[Meta Title] improve duplicate meta titles

### PR DESCRIPTION
**Pull request by jonatanvm**
## Issue

Screenshot 2024-12-02 at 15 42 03

We might need to change the title, b[ut Google docs say they also listen to og:title](https://developers.google.com/search/docs/appearance/title-link) so that might be enough.

### CODE REVIEW

**Review by louisjoecodes — CHANGES_REQUESTED** [review]
Can you please change Elevenlabs -> ElevenLabs - this then looks good to merge. Nicely spotted! Didn't know there was an override for OG this - will keep this in mind.

**Comment by louisjoecodes** [comment]
I just checked and this doesn't change change the og titles - but it changes the <title> tag which (I think) is used in the search engine i.e. <title>Conversational AI Introduction | ElevenLabs Docs</title> - so I think this should definitely have an impact

**Comment by jonatanvm** [comment]
> Can you please change Elevenlabs -> ElevenLabs - this then looks good to merge. Nicely spotted! Didn't know there was an override for meta titles - will keep this in mind.

Thank you, fixed!

**Comment by jonatanvm** [comment]
> I just checked and this doesn't change change the og titles - but it changes the <title> tag which (I think) is used in the search engine i.e. <title>Conversational AI Introduction | ElevenLabs Docs</title> - so I think this should definitely have an impact

Aaah didn't notice, that's excellent! 🤩

**Comment by louisjoecodes** [comment]
🔥

**Pull request merged**
