### PR TITLE
feat: Give Conversational AI docs navigate tool

### PR DESCRIPTION
**Pull request by louisjoecodes**
TODO: need to update prod agent & point to it if we want this live.

### CODE REVIEW

**Comment by louisjoecodes** [comment]
cc: @hikmet-demir & @OsKrg a fun one to test here :)

**Review by OsKrg — APPROVED** [review]
Tested and works great!

**Review by aarthificial — COMMENTED** [review]
The widget has an event for extending the call configuration which may be a bit cleaner here:
```ts
widget.addEventListener("elevenlabs-convai:call", event => {
  event.detail.config.clientTools = {
    redirect: ({path}) => {
      // navigate logic here
    }
  }
});
```

**Comment by louisjoecodes** [comment]
Thanks @aarthificial hadn't realised this!

**Pull request closed without merging**
